{{- if eq true .Values.firefox.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.firefox.fullname" . }}
  namespace: {{ .Values.global.nameSpace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.firefox.replicas }}
  selector:
    matchLabels:
      app: {{ template "selenium.firefox.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.firefox.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.firefox.image }}:{{ .Values.firefox.tag }}"
          imagePullPolicy: {{ .Values.firefox.pullPolicy }}
          ports:
            {{- if .Values.hub.jmxPort }}
            - containerPort: {{ .Values.hub.jmxPort }}
              name: jmx
              protocol: TCP
            {{- end }}
          env:
            - name: SE_EVENT_BUS_HOST
              value: {{ template "selenium.hub.fullname" . }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: HUB_PORT_4444_TCP_ADDR
              value: {{ template "selenium.hub.fullname" . }}
            - name: HUB_PORT_4444_TCP_PORT
              value: {{ .Values.hub.port | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ default "" .Values.firefox.javaOpts | quote }}
            - name: SE_OPTS
              value: {{ default "" .Values.firefox.seOpts | quote }}
            {{- if .Values.firefox.firefoxVersion }}
            - name: FIREFOX_VERSION
              value: {{ .Values.firefox.firefoxVersion | quote }}
            {{- end }}
            {{- if .Values.firefox.nodeMaxInstances }}
            - name: NODE_MAX_INSTANCES
              value: {{ .Values.firefox.nodeMaxInstances | quote }}
            {{- end }}
            {{- if .Values.firefox.nodeMaxSession }}
            - name: NODE_MAX_SESSION
              value: {{ .Values.firefox.nodeMaxSession | quote }}
            {{- end }}
            {{- if .Values.firefox.nodeRegisterCycle }}
            - name: NODE_REGISTER_CYCLE
              value: {{ .Values.firefox.nodeRegisterCycle | quote }}
            {{- end }}
            {{- if .Values.firefox.nodePort }}
            - name: NODE_PORT
              value: {{ .Values.firefox.nodePort | quote }}
            {{- end }}
            {{- if .Values.firefox.screenWidth }}
            - name: SCREEN_WIDTH
              value: {{ .Values.firefox.screenWidth | quote }}
            {{- end }}
            {{- if .Values.firefox.screenHeight }}
            - name: SCREEN_HEIGHT
              value: {{ .Values.firefox.screenHeight | quote }}
            {{- end }}
            {{- if .Values.firefox.screenDepth }}
            - name: SCREEN_DEPTH
              value: {{ .Values.firefox.screenDepth | quote }}
            {{- end }}
            {{- if .Values.firefox.display }}
            - name: DISPLAY
              value: {{ .Values.firefox.display | quote }}
            {{- end }}
            {{- if .Values.firefox.timeZone }}
            - name: TZ
              value: {{ .Values.firefox.timeZone | quote }}
            {{- end }}
            {{- if .Values.firefox.xvfb }}
            - name: START_XVFB
              value: {{ .Values.firefox.xvfb | quote }}
            {{- end }}
          volumeMounts:
{{ if .Values.firefox.volumeMounts -}}
{{ toYaml .Values.firefox.volumeMounts | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.firefox.resources | indent 12 }}
      volumes:
{{ if .Values.firefox.volumes -}}
{{ toYaml .Values.firefox.volumes | indent 8 }}
{{- end }}
      nodeSelector:
{{- if .Values.firefox.nodeSelector }}
{{ toYaml .Values.firefox.nodeSelector | indent 8  }}
{{- else if .Values.global.nodeSelector }}
{{ toYaml .Values.global.nodeSelector | indent 8  }}
{{- end }}
{{- end -}}
